branches:
  - "master"
ci: true
plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: build
          release: false
        - type: chore
          release: false
        - type: ci
          release: false
        - type: docs
          release: patch
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: refactor
          release: patch
        - type: test
          release: patch
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"